project:
  type: book
  output-dir: .

book:
  title: Masterthesis_doc
  date: May 05, 2026
  author:
    name: Lona Frie√üner
  downloads: [pdf]
  abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quis accumsan ante. Quisque lorem metus, varius id urna eget, lacinia dapibus sem. Etiam laoreet, quam ac mollis congue, arcu leo dictum neque, nec euismod sem enim luctus odio. Donec condimentum tortor sit amet mollis volutpat. Donec ornare libero vel velit malesuada consectetur. Vestibulum in sem non justo dignissim congue at quis erat. Integer quis erat vitae mi maximus fringilla tristique nec odio. Morbi non ipsum sapien. Vestibulum tortor est, ultricies in eros et, bibendum iaculis justo. Cras pellentesque enim quam, id pretium lacus lacinia non. Integer velit neque, ultrices a malesuada vel, imperdiet quis enim. Quisque eu facilisis urna, ut faucibus lorem. Donec mollis turpis sed arcu venenatis interdum. Nulla facilisis tortor ac scelerisque consequat."
  chapters:
    - index.qmd
    - chapters/theory.qmd
    - chapters/methods.qmd
    - chapters/results.qmd
    - chapters/discussion.qmd
    - references.qmd
  #appendices:
    #- appendices/AppendixA.qmd

  repo-url: https://github.com/lonalytical/masterthesis
  search: true

thesis:
  supervisor: 
    name: Prof. Dr. Simon Grund
  degree-name: Master of Science
  university: University of Hamburg
  department: Department of Psychology with focus on Quantitative Methods
  group: Institute of Psychology
  faculty: Institute of Psychology
  #declaration: "frontmatter/declaration.tex"
  #quotation:
  #  text: "Thanks to my solid academic training, today I can write hundreds of words on virtually any topic without possessing a shred of information, which is how I got a good job in journalism."
  #  attribution: Dave Barry
  #acknowledgements: "frontmatter/acknowledgements.tex"
  #abbreviations: "frontmatter/abbreviations.tex"
  #symbols: "frontmatter/symbols.tex"
  #dedication: "frontmatter/dedication.tex"
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [bibliography.bib]
csl: apa.csl

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf:
    urlcolor: blue
    toclinkcolor: black
    toc-depth: 2

